# Generated by Django 6.0.6 on 2026-07-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_radius_km', models.PositiveIntegerField(default=50, help_text='Maximum distance from current location in kilometers')),
                ('preferred_direction', models.CharField(choices=[('any', 'Any Direction'), ('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'North-East'), ('northwest', 'North-West'), ('southeast', 'South-East'), ('southwest', 'South-West')], default='any', max_length=20)),
                ('close_to_highway', models.BooleanField(default=False, verbose_name='Must be close to a main highway')),
                ('close_to_water_source', models.BooleanField(default=False, verbose_name='Must be close to a water source')),
                ('close_to_town', models.BooleanField(default=False, verbose_name='Must be close to a town/residential area')),
                ('intended_use', models.CharField(choices=[('any', 'Any Use'), ('agricultural', 'Agricultural / Farming'), ('residential', 'Residential / Construction'), ('commercial', 'Commercial / Warehouse / Industrial'), ('investment', 'Investment / Speculative')], default='any', max_length=20)),
                ('preferred_soil_type', models.CharField(choices=[('any', 'Any Soil Type'), ('loamy', 'Loamy Soil'), ('clayey', 'Clayey Soil'), ('sandy', 'Sandy Soil'), ('black', 'Black Soil'), ('red', 'Red Soil')], default='any', max_length=20)),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_budget', models.DecimalField(decimal_places=2, default=10000000, max_digits=14)),
                ('min_size_acres', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_size_acres', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
