# Generated by Django 6.0.6 on 2026-07-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buyerpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('min_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_condition', models.CharField(choices=[('never_leased', 'Never Leased'), ('previously_leased', 'Previously Leased'), ('no_preference', 'No Preference')], default='no_preference', max_length=50)),
                ('proximity_preferences', models.JSONField(blank=True, default=list)),
                ('required_amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BuyerPreference',
        ),
    ]
