# Generated by Django 6.0.6 on 2026-07-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_delete_buyerpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='required_amenities',
        ),
    ]
