# Generated by Django 6.0.6 on 2026-07-13 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_landownerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_doc_type_detected', models.BooleanField(blank=True, null=True)),
                ('aadhaar_number_found', models.BooleanField(blank=True, null=True)),
                ('aadhaar_number_match', models.BooleanField(blank=True, null=True)),
                ('aadhaar_ocr_number', models.CharField(blank=True, max_length=20)),
                ('aadhaar_confidence', models.FloatField(blank=True, null=True)),
                ('pan_doc_type_detected', models.BooleanField(blank=True, null=True)),
                ('pan_number_found', models.BooleanField(blank=True, null=True)),
                ('pan_number_match', models.BooleanField(blank=True, null=True)),
                ('pan_ocr_number', models.CharField(blank=True, max_length=15)),
                ('pan_confidence', models.FloatField(blank=True, null=True)),
                ('name_match_score', models.FloatField(blank=True, null=True)),
                ('dob_match', models.BooleanField(blank=True, null=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('failed', 'Failed')], max_length=20)),
                ('validation_flags', models.JSONField(blank=True, default=list)),
                ('aadhaar_raw_text', models.TextField(blank=True)),
                ('pan_raw_text', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'OCR Processing Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_validation', to='accounts.landownerapplication')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
