# Generated by Django 6.0.6 on 2026-08-05 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedLandownerFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('rejected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-rejected_at'],
            },
        ),
    ]
