# Generated by Django 6.0.6 on 2026-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rejectedlandownerflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landownerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landownerapplication',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
