# Generated by Django 6.0.6 on 2026-08-13 14:51

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_landownerapplication_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landownerapplication',
            name='aadhaar_document',
            field=models.FileField(upload_to=apps.accounts.models.get_landowner_doc_path),
        ),
        migrations.AlterField(
            model_name='landownerapplication',
            name='ownership_document',
            field=models.FileField(upload_to=apps.accounts.models.get_landowner_doc_path),
        ),
        migrations.AlterField(
            model_name='landownerapplication',
            name='pan_document',
            field=models.FileField(upload_to=apps.accounts.models.get_landowner_doc_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.get_profile_pic_path),
        ),
    ]
