# Generated by Django 6.0.6 on 2026-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='location',
            field=models.CharField(default='Sitapura, Jaipur', max_length=255),
        ),
        migrations.AddField(
            model_name='land',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
