# Generated by Django 6.0.6 on 2026-07-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_land_location_land_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='boundary_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='List of [lat, lng] pairs defining the boundary'),
        ),
        migrations.AddField(
            model_name='land',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='zoom_level',
            field=models.IntegerField(default=17),
        ),
    ]
