# Generated by Django 6.0.6 on 2026-07-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_land_boundary_coordinates_land_center_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('area', models.CharField(help_text='e.g. 1,500 sqft', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facing', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('North-East', 'North-East'), ('North-West', 'North-West'), ('South-East', 'South-East'), ('South-West', 'South-West')], default='North', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('coordinates', models.JSONField(help_text='List of [lat, lng] pairs defining the plot outline')),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='lands.land')),
            ],
            options={
                'ordering': ['plot_number'],
                'unique_together': {('land', 'plot_number')},
            },
        ),
    ]
