# Generated by Django 6.0.6 on 2026-07-03 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed information about the land, amenities, and surroundings'),
        ),
        migrations.CreateModel(
            name='EntryExitPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('point_type', models.CharField(choices=[('entry', 'Entry Point'), ('exit', 'Exit Point'), ('both', 'Entry & Exit Point')], default='entry', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.land')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coordinates', models.JSONField(help_text='JSON list of [lat, lng] coordinates defining the road path')),
                ('width_meters', models.DecimalField(decimal_places=1, default=9.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='lands.land')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
