# Generated by Django 6.0.6 on 2026-07-03 11:29

import apps.lands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_land_description_entryexitpoint_landimage_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='landimage',
            name='image',
            field=models.ImageField(upload_to=apps.lands.models.get_land_gallery_upload_path),
        ),
    ]
