# Generated by Django 6.0.6 on 2026-07-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0006_alter_land_name_alter_landimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('reserved', 'Reserved'),
                    ('sold', 'Sold'),
                    ('building', 'Building'),
                ],
                default='available',
                max_length=20,
            ),
        ),
    ]

