# Generated by Django 6.0.6 on 2026-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0007_alter_plot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='height',
            field=models.IntegerField(default=1, help_text='Building height (floors/multiplier) for 3D extrusion'),
        ),
    ]
