# Generated by Django 6.0.6 on 2026-07-06 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0008_plot_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='height',
        ),
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(help_text='Unique building identifier, e.g. Block-A, T-Court', max_length=50)),
                ('area', models.CharField(help_text='e.g. 0.3450 acres', max_length=50)),
                ('height', models.IntegerField(default=1, help_text='Number of floors for 3D extrusion')),
                ('coordinates', models.JSONField(help_text='List of [lat, lng] pairs defining the building footprint')),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='lands.land')),
            ],
            options={
                'ordering': ['building_id'],
                'unique_together': {('land', 'building_id')},
            },
        ),
    ]
