# Generated by Django 6.0.6 on 2026-07-06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0009_remove_plot_height_alter_plot_status_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
