# Generated by Django 6.0.6 on 2026-07-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0010_building_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='updated_at',
        ),
    ]
