# Generated by Django 6.0.6 on 2026-07-14 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0013_occupancyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLayoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('layout_file', models.FileField(upload_to='site_layouts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_layouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
