# Generated by Django 6.0.6 on 2026-07-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0014_sitelayoutplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitelayoutplan',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='uploaded', max_length=20),
        ),
    ]
