# Generated by Django 6.0.6 on 2026-07-16 10:21

import apps.lands.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0015_alter_sitelayoutplan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_live',
            field=models.BooleanField(default=False, help_text='If True, this property is visible to buyers in the directory.'),
        ),
        migrations.CreateModel(
            name='LandRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('google_maps_link', models.URLField(blank=True, help_text='Optional Google Maps link', null=True)),
                ('description', models.TextField(blank=True)),
                ('average_plot_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ownership_proof', models.FileField(help_text='Registry document, sale deed, or other ownership proof (PDF/image)', upload_to=apps.lands.models.get_ownership_proof_path)),
                ('floor_plan', models.FileField(help_text='Site layout / floor plan showing plot arrangement (PDF/image)', upload_to=apps.lands.models.get_floor_plan_path)),
                ('notes', models.TextField(blank=True, help_text="Landowner's notes to admin")),
                ('admin_remarks', models.TextField(blank=True, help_text='Internal admin notes (not shown to landowner)')),
                ('rejection_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('land', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='lands.land')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_reg_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='SiteLayoutPlan',
        ),
    ]
