# Generated by Django 6.0.6 on 2026-07-16 11:09

import apps.lands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0016_add_land_registration_request_remove_sitelayoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='city_village',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='complete_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='pin_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='registry_sale_deed',
            field=models.FileField(blank=True, help_text='Registry / Sale Deed document', null=True, upload_to=apps.lands.models.get_registry_sale_deed_path),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Additional supporting documents', null=True, upload_to=apps.lands.models.get_supporting_docs_path),
        ),
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('being_added', 'Being Added'), ('approved', 'Approved'), ('live', 'Live'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
