# Generated by Django 6.0.6 on 2026-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0017_landregistrationrequest_city_village_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('being_added', 'Being Added'), ('approved', 'Approved'), ('live', 'Live'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20),
        ),
    ]
