# Generated by Django 6.0.6 on 2026-07-17 14:45

import apps.lands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0018_add_deleted_status_to_landregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='plot_pricing_csv',
            field=models.FileField(blank=True, help_text='Plot sizing and pricing sheet (CSV)', null=True, upload_to=apps.lands.models.get_pricing_csv_path),
        ),
    ]
