# Generated by Django 6.0.6 on 2026-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0019_landregistrationrequest_plot_pricing_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='admin_message',
            field=models.TextField(blank=True, default='', help_text='Message or queries to landowner'),
        ),
    ]
