# Generated by Django 6.0.6 on 2026-07-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0020_landregistrationrequest_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='24-hour payment deadline after admin approval', null=True),
        ),
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('payment_pending', 'Payment Pending (24h)'), ('payment_completed', 'Payment Received — Awaiting Build'), ('being_added', 'Being Digitized'), ('approved', 'Approved'), ('live', 'Live'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=25),
        ),
    ]
