# Generated by Django 6.0.6 on 2026-07-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0021_landregistrationrequest_payment_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='24-hour payment deadline set after admin approval', null=True),
        ),
    ]
