# Generated by Django 6.0.6 on 2026-08-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0022_alter_landregistrationrequest_payment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('payment_pending', 'Payment Pending (24h)'), ('payment_completed', 'Payment Received — Awaiting Build'), ('being_added', 'Being Digitized'), ('approved', 'Approved'), ('awaiting_publish_approval', 'Awaiting Publish Approval'), ('live', 'Live'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=25),
        ),
    ]
