# Generated by Django 6.0.6 on 2026-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0023_alter_landregistrationrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='city_village',
            field=models.CharField(blank=True, default='', help_text='City or village where the land is located', max_length=150),
        ),
        migrations.AddField(
            model_name='land',
            name='state',
            field=models.CharField(blank=True, default='', help_text='State where the land is located', max_length=100),
        ),
    ]
