# Generated by Django 6.0.6 on 2026-08-11 13:08

import apps.lands.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0024_land_city_village_land_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending (24h)'), ('payment_completed', 'Payment Received'), ('being_added', 'Being Added'), ('approved', 'Approved'), ('awaiting_publish_approval', 'Awaiting Publish Approval'), ('live', 'Live'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='LandRegistrationGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.lands.models.get_request_gallery_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='lands.landregistrationrequest')),
            ],
        ),
    ]
