# Generated by Django 6.0.6 on 2026-08-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0025_alter_landregistrationrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='reupload_document',
            field=models.CharField(blank=True, choices=[('ownership_proof', 'Ownership Proof'), ('registry_sale_deed', 'Registry / Sale Deed'), ('supporting_documents', 'Supporting Documents'), ('floor_plan', 'Floor Plan')], default='', help_text='Which document the landowner must re-upload', max_length=30),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='reupload_note',
            field=models.TextField(blank=True, default='', help_text="Admin's note explaining what is wrong with the current document"),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='reupload_requested',
            field=models.BooleanField(default=False, help_text='Admin has asked the landowner to re-upload a document'),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='reupload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landregistrationrequest',
            name='reupload_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the landowner replaced the requested document', null=True),
        ),
    ]
