# Generated by Django 6.0.6 on 2026-08-15 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0026_landregistrationrequest_reupload_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotLeaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_name', models.CharField(max_length=200)),
                ('land_slug', models.CharField(blank=True, default='', max_length=150)),
                ('owner_username', models.CharField(max_length=150)),
                ('plot_number', models.CharField(max_length=50)),
                ('buyer_username', models.CharField(max_length=150)),
                ('event', models.CharField(choices=[('leased', 'Leased'), ('vacated', 'Vacated')], max_length=20)),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_at'],
            },
        ),
    ]
