# Generated by Django 6.0.6 on 2026-08-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0027_plotleaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='landregistrationrequest',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Monthly hosting fee set by admin', max_digits=10),
        ),
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Payment deadline set by admin; request auto-rejects if missed', null=True),
        ),
        migrations.AlterField(
            model_name='landregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Received'), ('being_added', 'Being Added'), ('approved', 'Approved'), ('awaiting_publish_approval', 'Awaiting Publish Approval'), ('live', 'Live'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=25),
        ),
    ]
