# Generated by Django 6.0.6 on 2026-07-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_ticket_ticketreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
