# Generated by Django 6.0.6 on 2026-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='land_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('land_delete_request', 'Land Deletion Request'), ('plot_delete_request', 'Plot Deletion Request'), ('request_rejected', 'Deletion Request Rejected'), ('request_approved', 'Deletion Request Approved')], default='land_delete_request', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='plot_kind',
            field=models.CharField(blank=True, help_text="'plot' or 'building'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='plot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
