# Generated by Django 6.0.6 on 2026-07-08 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_updated_at'),
        ('lands', '0011_remove_building_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('land_delete_request', 'Land Deletion Request'), ('plot_delete_request', 'Plot Deletion Request'), ('request_rejected', 'Deletion Request Rejected'), ('request_approved', 'Deletion Request Approved'), ('purchase_request', 'Purchase Request'), ('purchase_request_meeting', 'Meeting Scheduled'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_approved', 'Purchase Request Approved')], default='land_delete_request', max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('meeting_scheduled', 'Meeting Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('meeting_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='lands.land')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
