# Generated by Codex on 2026-07-08

from django.db import migrations, models


def mark_existing_read_requests_resolved(apps, schema_editor):
    Notification = apps.get_model('core', 'Notification')
    Notification.objects.filter(
        notif_type__in=['land_delete_request', 'plot_delete_request'],
        is_read=True,
    ).update(is_resolved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_read_requests_resolved, migrations.RunPython.noop),
    ]
