# Generated by Django 6.0.6 on 2026-07-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailotp_alter_notification_notif_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
