# Generated by Django 6.0.6 on 2026-07-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_purchaserequest_meet_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='google_event_id',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='meeting_time',
        ),
    ]
