# Generated by Django 6.0.6 on 2026-07-12 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_landownerapplication'),
        ('core', '0007_remove_purchaserequest_google_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='landowner_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.landownerapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('land_delete_request', 'Land Deletion Request'), ('plot_delete_request', 'Plot Deletion Request'), ('request_rejected', 'Deletion Request Rejected'), ('request_approved', 'Deletion Request Approved'), ('purchase_request', 'Purchase Request'), ('purchase_request_meeting', 'Meeting Scheduled'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_approved', 'Purchase Request Approved'), ('lo_registration_request', 'Landowner Registration Request'), ('lo_registration_approved', 'Landowner Registration Approved'), ('lo_registration_rejected', 'Landowner Registration Rejected')], default='land_delete_request', max_length=50),
        ),
    ]
