# Generated by Django 6.0.6 on 2026-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_ticket_id_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('land_delete_request', 'Land Deletion Request'), ('plot_delete_request', 'Plot Deletion Request'), ('request_rejected', 'Deletion Request Rejected'), ('request_approved', 'Deletion Request Approved'), ('purchase_request', 'Purchase Request'), ('purchase_request_meeting', 'Meeting Scheduled'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_approved', 'Purchase Request Approved'), ('lo_registration_request', 'Landowner Registration Request'), ('lo_registration_approved', 'Landowner Registration Approved'), ('lo_registration_rejected', 'Landowner Registration Rejected'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_replied', 'Support Ticket Reply'), ('support_ticket_status_changed', 'Support Ticket Status Changed'), ('purchase_request_cancelled', 'Purchase Request Cancelled')], default='land_delete_request', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('meeting_scheduled', 'Meeting Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
