# Generated by Django 6.0.6 on 2026-07-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ticket_ticketreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
    ]
