# Generated by Django 6.0.6 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='buyer_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
