# Generated by Django 6.0.6 on 2026-08-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notification_notif_type_deallotmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('land_delete_request', 'Land Deletion Request'), ('plot_delete_request', 'Plot Deletion Request'), ('request_rejected', 'Deletion Request Rejected'), ('request_approved', 'Deletion Request Approved'), ('purchase_request', 'Purchase Request'), ('purchase_request_meeting', 'Meeting Scheduled'), ('purchase_request_rejected', 'Purchase Request Rejected'), ('purchase_request_approved', 'Purchase Request Approved'), ('lo_registration_request', 'Landowner Registration Request'), ('lo_registration_approved', 'Landowner Registration Approved'), ('lo_registration_rejected', 'Landowner Registration Rejected'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_replied', 'Support Ticket Reply'), ('support_ticket_status_changed', 'Support Ticket Status Changed'), ('purchase_request_cancelled', 'Purchase Request Cancelled'), ('doc_reupload_requested', 'Document Re-upload Requested'), ('doc_reupload_submitted', 'Document Re-uploaded'), ('doc_reupload_disabled', 'Document Re-upload Closed'), ('purchase_request_ocr', 'Purchase Request OCR Verified'), ('deallot_request_sent', 'De-allotment Request Sent'), ('deallot_request_approved', 'De-allotment Approved'), ('deallot_request_declined', 'De-allotment Declined'), ('buyer_deleted', 'Buyer Account Deleted'), ('landowner_deleted', 'Landowner Account Deleted')], default='land_delete_request', max_length=50),
        ),
    ]
